# Generated by Django 4.2.4 on 2024-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('size', models.CharField(max_length=3, verbose_name='Talla')),
                ('cost', models.FloatField(max_length=20, verbose_name='Valor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/photo/%Y/%m/%d', verbose_name='Foto')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('public', models.CharField(choices=[('Hombres', 'Hombres'), ('Mujeres', 'Mujeres'), ('Niños', 'Niños')], help_text='Seleccione el publico preferido', max_length=10, verbose_name='Publico preferido')),
                ('category', models.ManyToManyField(to='inv.category')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
