# Generated by Django 4.2.4 on 2024-03-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de reporte')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('answer', models.TextField(max_length=500, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'pqrs',
                'verbose_name_plural': 'pqrs',
                'db_table': 'pqrs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='Estado actual')),
                ('desciption', models.TextField(max_length=500, verbose_name='Descpripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado_pqrs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Tipo de PQRS')),
                ('desciption', models.TextField(max_length=500, verbose_name='Descpripción')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
    ]
