# Generated by Django 4.2.4 on 2024-03-30 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PQRS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PQRS.status', verbose_name='Estado actual'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PQRS.type', verbose_name='Tipo de PQRS'),
        ),
    ]
