# Generated by Django 4.2.4 on 2024-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='type_pqrs',
            field=models.CharField(choices=[('Petición', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], default='Petición', help_text='Seleccione su tipo de QPRS', max_length=10, verbose_name='Tipo de pqrs'),
        ),
    ]
