# Generated by Django 4.2.4 on 2024-03-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0003_remove_type_desciption_remove_type_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id'], 'verbose_name': 'Tipo_pqrs', 'verbose_name_plural': 'Tipos_pqrs'},
        ),
    ]
