# Generated by Django 4.2.4 on 2024-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0004_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte'),
        ),
    ]
