# Generated by Django 4.2.4 on 2024-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0005_alter_pqrs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='answer',
            field=models.TextField(blank=True, max_length=500, verbose_name='Respuesta'),
        ),
    ]
