# Generated by Django 4.2.4 on 2024-03-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0006_alter_pqrs_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PQRS.status', verbose_name='Estado actual'),
        ),
    ]
