# Generated by Django 4.2.4 on 2024-03-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0007_alter_pqrs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='answer',
            field=models.TextField(max_length=500, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PQRS.status', verbose_name='Estado actual'),
        ),
    ]
