# Generated by Django 4.2.4 on 2024-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0008_alter_pqrs_answer_alter_pqrs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='desciption',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('En trámite', 'En trámite'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='En trámite', max_length=10, verbose_name='Estado actual'),
        ),
    ]
